[package]
edition = "2021"
name = "jsonish"
version.workspace = true
authors.workspace = true
description.workspace = true
autotests = false
autobenches = false

license-file.workspace = true

[lints.rust]
dead_code = "allow"
mismatched_lifetime_syntaxes = "deny"
unused_imports = "allow"
unused_variables = "allow"

[lints.clippy]
type_complexity = "allow"

[lib]
test = false

[dependencies]
anyhow.workspace = true
baml-types.workspace = true
bstd.workspace = true
colored.workspace = true
pest.workspace = true
indoc.workspace = true
internal-baml-jinja.workspace = true
log.workspace = true
indexmap.workspace = true
strsim.workspace = true
serde_json.workspace = true
serde.workspace = true
# jsonschema = "0.17.1"
either.workspace = true
test-log.workspace = true
regex.workspace = true
minijinja.workspace = true
thiserror.workspace = true
unicode-normalization.workspace = true
cowstr.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { workspace = true, features = ["v4", "js"] }
getrandom = { version = "0.2.15", features = ["js"] }

[dev-dependencies]
assert-json-diff = "2.0.2"
wasm-bindgen-test = "0.3"
peak_alloc = "0.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { version = "0.5", default-features = false, features = ["html_reports", "plotters", "cargo_bench_support"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
criterion = { version = "0.5", default-features = false }
web-sys = { version = "0.3", features = ["console", "Performance", "Window"] }

[[bench]]
name = "jsonish_benchmark"
harness = false
required-features = []

[[bench]]
name = "unions"
harness = false

[[bench]]
name = "browser_bench"
harness = false
required-features = []
